apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-juan
spec:
  selector:
    app: juan-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort 